version: 2
sources:
  - name: Prello
    schema: Prello2023
    description: main project raw data
    tables:
      - name: poi_establishments
        identifier: POI_tourist_establishments
        description: primary key is municipality code
      - name: poi_sites
        identifier: POI_touristic_sites_by_municipality
        description: primary key is municipality code
        
      - name: geo_loc
        identifier: geographical_referential
        description: primary key is municipality code
      - name: notary
        identifier: notary_real_estate_sales
        description: primary key is municipality code
      - name: housing_stock
        identifier: housing_stock
        description: primary key is municipality code
      - name: real_estate_info_by_municipality
        identifier: real_estate_info_by_municipality
        description: primary key is municipality code
      - name: train_station
        identifier: train_station
        description: list of train station
      - name: Housing
        identifier: Housing_tables_2018_2022
        description: list of housing market
      - name: tourism_scoring
        identifier: score_tourism_normalized
        description: data table with diversity score normalized
      - name: tourism_scoring_sq
        identifier: score_tourism_normalized_sq
        description: data table with diversity score normalized and nb sites squared
      - name: tgv_train_station
        identifier: tgv_train_station
        description: data table with dinfo for TGV train station only
      - name: trainstation_cat
        identifier : train_station_cat_nb
        description: categorization of the train station by their territory cover and usage nb

